[build]
  command = "node -v && npm -v && npm ci --legacy-peer-deps && npm run postinstall && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps --no-optional --prefer-offline"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://edenclinic.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
