[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.11.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
