[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "20.11.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_SHARP_PATH = "./node_modules/sharp"
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-3.0.x,debian-openssl-1.1.x,linux-musl-openssl-3.0.x"
  NPM_FLAGS = "--legacy-peer-deps"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "false"
  PRISMA_GENERATE_DATAPROXY = "true"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production]
  command = "npm run build"
