[build]
  command = "npm install prisma && npx prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"
