[build]
  command = "npm install && npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.11.1"
  PRISMA_ENGINES_VERSION = "5.10.2"
  PRISMA_LOG_LEVEL = "info"
  PRISMA_LOG_QUERIES = "false"
  PRISMA_ENABLE_TRACING = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--no-audit --no-fund --legacy-peer-deps"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://eden-clinic-blood-tests.netlify.app"
  # Environment variables are set in Netlify UI

[build.processing]
  skip_processing = false

[functions]
  included_files = ["node_modules/@prisma/client/**/*", "node_modules/.prisma/**/*"]

[build.processing.html]
  pretty_urls = true
