[build]
  command = "npm ci && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.1"
  PRISMA_ENGINES_VERSION = "5.22.0"
  PRISMA_LOG_LEVEL = "info"
  PRISMA_LOG_QUERIES = "false"
  PRISMA_ENABLE_TRACING = "false"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://eden-clinic.windsurf.build"
  SENDGRID_API_KEY = "${env:SENDGRID_API_KEY}"
  STRIPE_SECRET_KEY = "${env:STRIPE_SECRET_KEY}"
  STRIPE_WEBHOOK_SECRET = "${env:STRIPE_WEBHOOK_SECRET}"
  SUPPORT_EMAIL = "${env:SUPPORT_EMAIL}"
  DATABASE_URL = "postgresql://postgres.dlzfhnnwyvddaoikrung:DNE8ytm_uyw1jbc*qbr@aws-0-eu-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
  DIRECT_URL = "postgresql://postgres.dlzfhnnwyvddaoikrung:DNE8ytm_uyw1jbc*qbr@aws-0-eu-west-2.pooler.supabase.com:5432/postgres"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing.html]
  pretty_urls = true

[[edge_functions]]
  function = "next-server"
  pattern = "/*"

[functions]
  included_files = ["node_modules/@prisma/client/**/*", "node_modules/.prisma/**/*"]

[build.processing]
  skip_processing = false
