[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Node.js configuration
  NODE_VERSION = "18.17.1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Prisma configuration
  PRISMA_ENGINES_VERSION = "5.10.2"
  PRISMA_LOG_LEVEL = "info"
  PRISMA_LOG_QUERIES = "false"
  PRISMA_ENABLE_TRACING = "false"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"
  
  # Next.js configuration
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_SHARP_PATH = "./node_modules/sharp"
  
  # Application URLs
  NEXT_PUBLIC_API_URL = "https://eden-clinic-blood-test-app.windsurf.build"
  NEXT_PUBLIC_BASE_URL = "https://eden-clinic-blood-test-app.windsurf.build"
  BASE_URL = "https://eden-clinic-blood-test-app.windsurf.build"
  
  # Email configuration
  SENDGRID_FROM_EMAIL = "admin@edenclinicformen.com"
  SUPPORT_EMAIL = "support@edenclinicformen.com"
  FORCE_REAL_EMAILS = "true"
  
  # Feature flags
  ENABLE_TEST_DATA_CLEANUP = "false"
  ENABLE_USER_DELETION = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  # Environment variables are set in Netlify UI

# Processing options already defined above

# Include Prisma files in functions
[functions]
  included_files = ["node_modules/@prisma/client/**/*", "node_modules/.prisma/**/*"]
  node_bundler = "esbuild"

# Pretty URLs setting already moved to main build.processing section

# Next.js plugin configuration is already defined above

# Handle static assets with specific redirects
[[redirects]]
  from = "/_next/static/css/*"
  to = "/.next/static/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/static/chunks/*"
  to = "/.next/static/chunks/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/static/*"
  to = "/.next/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/_next/*"
  to = "/.next/_next/:splat"
  status = 200
  force = true

# Redirect API routes properly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

# Let Next.js handle client-side routing
# The Next.js plugin will add the necessary redirects

# Force HTTPS
[[redirects]]
  from = "http://eden-clinic-blood-test-app.windsurf.build/*"
  to = "https://eden-clinic-blood-test-app.windsurf.build/:splat"
  status = 301
  force = true
